# Generated by Django 3.2 on 2021-07-12 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemKind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(help_text='type of the item ', max_length=50, verbose_name='Type')),
            ],
        ),
        migrations.CreateModel(
            name='Smiths',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smith', models.CharField(help_text='smith who made the item', max_length=50, verbose_name='Smith')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Names')),
                ('height', models.IntegerField(help_text='how tall is the item in cm ', verbose_name='Height')),
                ('whith', models.IntegerField(help_text='how wide is the item in cm', verbose_name='Whith')),
                ('lenght', models.IntegerField(help_text='how wide is the item in cm', verbose_name='Lenght')),
                ('description', models.CharField(max_length=400, verbose_name='Description')),
                ('city', models.CharField(help_text='city where item can be picked up', max_length=200, verbose_name='City')),
                ('price', models.IntegerField(help_text='price in euro', verbose_name='Price')),
                ('image', models.ImageField(null=True, upload_to='img', verbose_name='foto')),
                ('name2', models.CharField(max_length=200, verbose_name='Names2')),
                ('smith_id', models.ForeignKey(help_text='who made the item', max_length=50, null=True, on_delete=django.db.models.deletion.SET_NULL, to='smith.smiths')),
                ('type_id', models.ForeignKey(help_text='type of the item', max_length=50, null=True, on_delete=django.db.models.deletion.SET_NULL, to='smith.itemkind')),
            ],
        ),
    ]
