# Generated by Django 3.2 on 2021-07-24 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('body', models.TextField(null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GaleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='Names')),
                ('description', models.CharField(max_length=200, null=True, verbose_name='Description')),
                ('image', models.ImageField(null=True, upload_to='img', verbose_name='main foto')),
            ],
        ),
        migrations.CreateModel(
            name='Landing_photos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='img', verbose_name='third')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='Names')),
                ('height', models.IntegerField(help_text='how tall is the item in cm ', null=True, verbose_name='Height')),
                ('whith', models.IntegerField(help_text='how wide is the item in cm', null=True, verbose_name='Whith')),
                ('lenght', models.IntegerField(help_text='how wide is the item in cm', null=True, verbose_name='Lenght')),
                ('description', models.CharField(max_length=400, null=True, verbose_name='Description')),
                ('price', models.IntegerField(help_text='price in euro', null=True, verbose_name='Price')),
                ('image', models.ImageField(null=True, upload_to='img', verbose_name='main image')),
            ],
        ),
        migrations.CreateModel(
            name='product_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(help_text='type', max_length=50, null=True, verbose_name='Type')),
            ],
        ),
        migrations.CreateModel(
            name='Smiths',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smith', models.CharField(help_text='smith who made the item', max_length=50, null=True, verbose_name='Smith')),
                ('mobile_number', models.CharField(max_length=12, null=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(null=True, upload_to='img')),
                ('product', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='smith.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='smith_id',
            field=models.ForeignKey(help_text='who made the item', max_length=50, null=True, on_delete=django.db.models.deletion.SET_NULL, to='smith.smiths'),
        ),
        migrations.CreateModel(
            name='GaleryImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(null=True, upload_to='img')),
                ('GaleryItem', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='smith.galeryitem')),
            ],
        ),
    ]
