# Generated by Django 3.2 on 2021-07-24 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smith', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_Types',
            field=models.ManyToManyField(to='smith.product_Type'),
        ),
    ]
