# Generated by Django 3.2 on 2021-07-24 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smith', '0002_product_product_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_Types',
        ),
        migrations.AddField(
            model_name='galeryitem',
            name='product_Types',
            field=models.ManyToManyField(to='smith.product_Type'),
        ),
        migrations.AlterField(
            model_name='smiths',
            name='mobile_number',
            field=models.CharField(max_length=12, null=True, verbose_name='Mobile number'),
        ),
    ]
