# Generated by Django 3.2 on 2021-07-12 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smith', '0003_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='GaleryItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Names')),
                ('description', models.CharField(max_length=200, verbose_name='Names')),
                ('image', models.ImageField(null=True, upload_to='img', verbose_name='foto')),
            ],
        ),
    ]
