# Generated by Django 3.2 on 2021-07-24 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smith', '0004_auto_20210724_1853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='galeryimages',
            old_name='GaleryItem',
            new_name='galeryitem',
        ),
    ]
