# Generated by Django 3.2 on 2021-07-12 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smith', '0004_galeryitems'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GaleryItems',
            new_name='GaleryItem',
        ),
    ]
