# Generated by Django 3.2 on 2021-07-12 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smith', '0005_rename_galeryitems_galeryitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galeryitem',
            name='description',
            field=models.CharField(max_length=200, verbose_name='Description'),
        ),
    ]
