# Generated by Django 3.2 on 2021-07-26 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smith', '0007_auto_20210726_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.CharField(max_length=400, null=True, verbose_name='Description_en'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=400, null=True, verbose_name='Description_lt'),
        ),
    ]
