# Generated by Django 3.2 on 2021-07-13 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smith', '0007_auto_20210713_1127'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostProduct',
            new_name='ProductImages',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to='img', verbose_name='main image'),
        ),
    ]
