# Generated by Django 3.2 on 2021-07-14 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smith', '0009_auto_20210713_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='galeryitem',
            name='image2',
            field=models.ImageField(null=True, upload_to='img', verbose_name='secondary image'),
        ),
        migrations.AddField(
            model_name='galeryitem',
            name='image3',
            field=models.ImageField(null=True, upload_to='img', verbose_name='secondary image'),
        ),
        migrations.AddField(
            model_name='galeryitem',
            name='image4',
            field=models.ImageField(null=True, upload_to='img', verbose_name='secondary image'),
        ),
        migrations.AddField(
            model_name='galeryitem',
            name='image5',
            field=models.ImageField(null=True, upload_to='img', verbose_name='secondary image'),
        ),
        migrations.AddField(
            model_name='galeryitem',
            name='image6',
            field=models.ImageField(null=True, upload_to='img', verbose_name='secondary image'),
        ),
        migrations.AddField(
            model_name='galeryitem',
            name='image7',
            field=models.ImageField(null=True, upload_to='img', verbose_name='secondary image'),
        ),
        migrations.AddField(
            model_name='galeryitem',
            name='image8',
            field=models.ImageField(null=True, upload_to='img', verbose_name='secondary image'),
        ),
    ]
