# Generated by Django 3.2 on 2021-07-19 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smith', '0012_auto_20210714_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galeryitem',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='galeryitem',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='galeryitem',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='galeryitem',
            name='image5',
        ),
        migrations.RemoveField(
            model_name='galeryitem',
            name='image6',
        ),
        migrations.RemoveField(
            model_name='galeryitem',
            name='image7',
        ),
        migrations.RemoveField(
            model_name='galeryitem',
            name='image8',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image5',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image6',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image7',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image8',
        ),
    ]
