# Generated by Django 3.2 on 2021-07-19 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smith', '0013_auto_20210719_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('body', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
